[2024-06-08T09:35:30.973+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_toll_data_17.load_to_database manual__2024-06-08T09:17:10.411004+00:00 [queued]>
[2024-06-08T09:35:30.996+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_toll_data_17.load_to_database manual__2024-06-08T09:17:10.411004+00:00 [queued]>
[2024-06-08T09:35:30.996+0000] {taskinstance.py:1331} INFO - Starting attempt 6 of 7
[2024-06-08T09:35:31.021+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): load_to_database> on 2024-06-08 09:17:10.411004+00:00
[2024-06-08T09:35:31.028+0000] {standard_task_runner.py:57} INFO - Started process 679 to run task
[2024-06-08T09:35:31.034+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data_17', 'load_to_database', 'manual__2024-06-08T09:17:10.411004+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/ETL_toll_data.py', '--cfg-path', '/tmp/tmprx508oul']
[2024-06-08T09:35:31.038+0000] {standard_task_runner.py:85} INFO - Job 187: Subtask load_to_database
[2024-06-08T09:35:31.111+0000] {task_command.py:410} INFO - Running <TaskInstance: ETL_toll_data_17.load_to_database manual__2024-06-08T09:17:10.411004+00:00 [running]> on host bec75c81cc74
[2024-06-08T09:35:31.563+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='dummy@gmail.com' AIRFLOW_CTX_DAG_OWNER='naveed' AIRFLOW_CTX_DAG_ID='ETL_toll_data_17' AIRFLOW_CTX_TASK_ID='load_to_database' AIRFLOW_CTX_EXECUTION_DATE='2024-06-08T09:17:10.411004+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-08T09:17:10.411004+00:00'
[2024-06-08T09:35:31.570+0000] {logging_mixin.py:149} INFO - database connected successfully
[2024-06-08T09:35:35.690+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-06-08T09:35:35.726+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=ETL_toll_data_17, task_id=load_to_database, execution_date=20240608T091710, start_date=20240608T093530, end_date=20240608T093535
[2024-06-08T09:35:35.892+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2024-06-08T09:35:36.021+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
